version: '3.7'

services:

  postgres:
    build:
      context: .
    # container_name: ${PG_CONTAINER_NAME}
    hostname: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - db_booking:/data/postgres-booking
    ports:
      - 5432:5432
    restart: always
    networks:
      - dbase-network

  pgadmin:
    image: dpage/pgadmin4:6
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on:
      - postgres
    restart: always
    networks:
      - dbase-network

volumes:
    db_booking:

networks:
  dbase-network: