version: '3.7'

services:
  # postgres:
  #   image: bitnami/postgresql:14
  #   networks:
  #     - dbase-network

  postgres:
    build:
      context: .
    # image: "postgres-tutorials"
    # container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - db_booking:/data/postgres-booking
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
    db_booking:
      external: true

networks:
  dbase-network: